name: warble
base: core24
adopt-info: warble
grade: stable
confinement: strict
compression: lzo
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

layout:
  /usr/share/com.github.avojak.warble:
    bind: $SNAP/usr/share/com.github.avojak.warble

slots:
  # for GtkApplication registration
  warble:
    interface: dbus
    bus: session
    name: com.github.avojak.warble

parts:
  warble:
    source: https://github.com/avojak/warble.git
    source-tag: 2.0.1
    plugin: meson
    meson-parameters: [ --prefix=/usr ]
    parse-info: [usr/share/metainfo/com.github.avojak.warble.appdata.xml]
    build-packages:
      - libgranite-7-dev
    override-pull: |
      craftctl default
      sed -i.bak -e 's|Icon=@icon@|Icon=${SNAP}/meta/gui/warble.svg|g' $CRAFT_PART_SRC/data/com.github.avojak.warble.desktop.in.in
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui/
      cp $CRAFT_PART_SRC/data/assets/icons/128x128/com.github.avojak.warble.svg $CRAFT_PART_INSTALL/meta/gui/warble.svg
  libraries:
    plugin: nil
    stage-packages:
      - libgranite-7-7
    prime:
      - usr/lib/*/libgrani*

apps:
  warble:
    extensions: [gnome]
    desktop: usr/share/applications/com.github.avojak.warble.desktop
    command: usr/bin/com.github.avojak.warble
    common-id: com.github.avojak.warble
